create table if not exists post_offices (
    zip_code bigint not null primary key,
    name varchar(1024) not null,
    post_address varchar(2048) not null
);

create table if not exists sendings (
    id bigint generated by default as identity not null primary key,
    type varchar(32) not null,
    receiver_zip_code bigint not null references post_offices(zip_code),
    receiver_address varchar(2048) not null,
    receiver_name varchar(1024) not null
);
